### ISSUE TITLE
Document non-obvious compose file env variables

### ISSUE THREAD

**Issue by Nitrousoxide** [ElryGH/docker-FMD2#1]
This was an issue with the original repo, but just noticed it here now that it's been like 6 months since I looked at this and had to remember what they do.

These two:

```
      - THRESHOLD_MINUTES=5
      - TRANSFER_FILE_TYPE=.cbz
```

aren't especially obvious to a user what they are for.  I remember them being for the transferring workaround.  Since we wanted it to only transfer the completed cbz (or pdf, or whatever) files rather than partially complete downloads.  The user will need to change the .cbz env variable if they chose other download formats, like raw jpg/pdf/etc so that it correctly transfers them.

I actually didn't have a threshhold minutes env variable in my local version, but I assume this is the timeout for the transfer workout?  Or the frequency that it checks for new files to transfer?

**Comment by ElryGH** [comment]
This is the frequency to check for files that are done, to then move them to the destination folder, the file type needs to be modified if you want to download as a zip or as epub file instead.
I dont think its going to be necessary to really tell people what it does, seems rather obvious to me.
But i can add a little hint behind it what it does exactly.
