### ISSUE TITLE
remote path mapping not working

### ISSUE THREAD

**Issue by quixotic120** [ElryGH/docker-FMD2#2]
hello,

thanks for this branch and for notifying me of it's existence in https://github.com/dazedcat19/FMD2/issues/1487#issuecomment-2383489408

Happy to report that all the modules I tried, including bato, work.

However, whenever I map to a remote path I get an error that the folder cannot be created. If I download to the containers app/FMD2/downloads directory things download fine but when I try to map downloads to another directory it consistently fails regardless of module. 

tried on both unraid and macOS docker with same issue in both. with the path bound allowing the app to download to the default /downloads directory just stores everything within the container. I can navigate to the directory and see files from my mapped folder but it won't write to it

I thought this may be a permissions issue on my end - set directory to drwxrwxrwx

also tried mapping both /downloads and /app/FMD2/downloads. both result in the same behavior except with the latter i can't download to the app container anymore, obviously.

edit: apologies for accidentally closing! I am clumsy. also tried setting umask to 002 with no benefit and have tried PGID and PUID as 1000:1000 and 100:99 (for unraid), same behavior. oddly this seems specific to downloads as my user settings are saved with the user data path mapped remotely

**Comment by ElryGH** [comment]
This is an issue with alpine and remote folders (prolly your nas), this is not something i can change in the image to adjust for, you need to set up the container differently, just google about docker and remote folders.

I found think something like this should work ?
Or just using NFS when the NAS is local.

```yml
volumes:
  folder:
    driver_opts:
      type: cifs
      o: username={smbuser},password={smbpass},uid={UID for mount},gid={gid for mount},vers=3.0
      device: //Share1/FolderMix
```

**Comment by ElryGH** [comment]
Sounds lime you are changing the download path in wine ?
Thats not what youre supposed to do, since there is a Script in this image to copy the files from the wine downloads to the actual download folder thats a volume.

You need to change the left path of the volume in docker compose:
changeme:/downloads

**Comment by ElryGH** [comment]
Also Docker Alpine doesnt play well with networkee devices, you need to correctly bind them to a volume in the way docker describes to mount remote folders to volumes.

I cant change anything in the image to make that work, its on your side.

**Comment by ElryGH** [comment]
The only thing i can do here is add a disclaimer to the docker compose
