### ISSUE TITLE
Unable to download manga list from server.

### ISSUE THREAD

**Issue by lyingloverr** [ElryGH/docker-FMD2#4]
When attempting to download a manga list server the error pictured below is received

![image](https://github.com/user-attachments/assets/638f9f72-8a5a-4599-a47c-75f4ed724ef3)

Manga List in side panel shows no manga on any connected websites.

**Comment by ElryGH** [comment]
does your instance say 2.0.33.0 at the top or still 2.0.32.0

**Comment by ElryGH** [comment]
Since FMD2 put out an update, could be that its an FMD2 error and not

**Comment by lyingloverr** [comment]
updated to 2.0.33.0 and its fixed, thanks

**Comment by ElryGH** [comment]
Please make sure that you update the docker image and not click Update FMD2 on the web interface.
